-- set_names: 系列名稱 (en/zh)，由 TCGdex en + zh-tw + 內建 kSetNameZh 合併而來。
create table if not exists set_names (
  set_id text primary key,
  en text,
  zh text
);

alter table set_names enable row level security;
drop policy if exists set_names_read on set_names;
create policy set_names_read on set_names for select using (true);

insert into set_names (set_id, en, zh) values
  ('2011bw', 'McDonald''s Collection 2011', null),
  ('2012bw', 'McDonald''s Collection 2012', null),
  ('2014xy', 'McDonald''s Collection 2014', null),
  ('2015xy', 'McDonald''s Collection 2015', null),
  ('2016xy', 'McDonald''s Collection 2016', null),
  ('2017sm', 'McDonald''s Collection 2017', null),
  ('2018sm', 'McDonald''s Collection 2018', null),
  ('2019sm', 'McDonald''s Collection 2019', null),
  ('2021swsh', 'McDonald''s Collection 2021', null),
  ('2022swsh', 'McDonald''s Collection 2022', null),
  ('2023sv', 'McDonald''s Collection 2023', null),
  ('2024sv', 'McDonald''s Collection 2024', null),
  ('a1', 'Genetic Apex', null),
  ('a1a', 'Mythical Island', null),
  ('a2', 'Space-Time Smackdown', null),
  ('a2a', 'Triumphant Light', null),
  ('a2b', 'Shining Revelry', null),
  ('a3', 'Celestial Guardians', null),
  ('a3a', 'Extradimensional Crisis', null),
  ('a3b', 'Eevee Grove', null),
  ('a4', 'Wisdom of Sea and Sky', null),
  ('a4a', 'Secluded Springs', null),
  ('b1', 'Mega Rising', null),
  ('b1a', 'Crimson Blaze', null),
  ('b2', 'Fantastical Parade', null),
  ('b2a', 'Paldean Wonders', null),
  ('base1', 'Base Set', null),
  ('base2', 'Jungle', null),
  ('base3', 'Fossil', null),
  ('base4', 'Base Set 2', null),
  ('base5', 'Team Rocket', null),
  ('basep', 'Wizards Black Star Promos', null),
  ('bog', 'Best of game', null),
  ('bw', null, '黑與白'),
  ('bw-p', null, '黑白 PROMO'),
  ('bw1', 'Black & White', '黑'),
  ('bw10', 'Plasma Blast', '銀色鏡子'),
  ('bw11', 'Legendary Treasures', '盛大的爭奪'),
  ('bw2', 'Emerging Powers', '白'),
  ('bw3', 'Noble Victories', '復甦的神話'),
  ('bw4', 'Next Destinies', '龍之鋒爪'),
  ('bw5', 'Dark Explorers', '煌翔的勝利'),
  ('bw6', 'Dragons Exalted', '寒冰突擊'),
  ('bw7', 'Boundaries Crossed', '冷冽鬥氣'),
  ('bw8', 'Plasma Storm', '極速進攻'),
  ('bw9', 'Plasma Freeze', '超越時空'),
  ('bwp', 'BW Black Star Promos', null),
  ('cel25', 'Celebrations', null),
  ('col1', 'Call of Legends', null),
  ('cs1.5', null, '三連音爆'),
  ('cs1a', null, '三連音爆'),
  ('cs1b', null, '三連音爆'),
  ('cs2.5', null, '三連音爆'),
  ('cs2a', null, '三連音爆'),
  ('cs2b', null, '三連音爆'),
  ('cs3.5', null, '三連音爆'),
  ('dc1', 'Double Crisis', null),
  ('det1', 'Detective Pikachu', null),
  ('dp', null, '鑽石與珍珠'),
  ('dp-p', null, '鑽石珍珠 PROMO'),
  ('dp1', 'Diamond & Pearl', null),
  ('dp2', 'Mysterious Treasures', null),
  ('dp3', 'Secret Wonders', null),
  ('dp4', 'Great Encounters', null),
  ('dp5', 'Majestic Dawn', null),
  ('dp6', 'Legends Awakened', null),
  ('dp7', 'Stormfront', null),
  ('dpp', 'DP Black Star Promos', null),
  ('dv1', 'Dragon Vault', null),
  ('ecard1', 'Expedition Base Set', null),
  ('ecard2', 'Aquapolis', null),
  ('ecard3', 'Skyridge', null),
  ('ex1', 'Ruby & Sapphire', null),
  ('ex10', 'Unseen Forces', null),
  ('ex11', 'Delta Species', null),
  ('ex12', 'Legend Maker', null),
  ('ex13', 'Holon Phantoms', null),
  ('ex14', 'Crystal Guardians', null),
  ('ex15', 'Dragon Frontiers', null),
  ('ex16', 'Power Keepers', null),
  ('ex2', 'Sandstorm', null),
  ('ex3', 'Dragon', null),
  ('ex4', 'Team Magma vs Team Aqua', null),
  ('ex5', 'Hidden Legends', null),
  ('ex5.5', 'Poké Card Creator Pack', null),
  ('ex6', 'FireRed & LeafGreen', null),
  ('ex7', 'Team Rocket Returns', null),
  ('ex8', 'Deoxys', null),
  ('ex9', 'Emerald', null),
  ('exu', 'Unseen Forces Unown Collection', null),
  ('fut2020', 'Pokémon Futsal 2020', null),
  ('g1', 'Generations', null),
  ('gym1', 'Gym Heroes', null),
  ('gym2', 'Gym Challenge', null),
  ('hgss1', 'HeartGold SoulSilver', null),
  ('hgss2', 'Unleashed', null),
  ('hgss3', 'Undaunted', null),
  ('hgss4', 'Triumphant', null),
  ('hgssp', 'HGSS Black Star Promos', null),
  ('jumbo', 'Jumbo cards', null),
  ('lc', 'Legendary Collection', null),
  ('me01', 'Mega Evolution', null),
  ('me02', 'Phantasmal Flames', null),
  ('me02.5', 'Ascended Heroes', null),
  ('me03', 'Perfect Order', null),
  ('me04', 'Chaos Rising', null),
  ('mee', 'Mega Evolution Energy', null),
  ('mep', 'MEP Black Star Promos', null),
  ('mfb', 'My First Battle', null),
  ('neo1', 'Neo Genesis', null),
  ('neo2', 'Neo Discovery', null),
  ('neo3', 'Neo Revelation', null),
  ('neo4', 'Neo Destiny', null),
  ('np', 'Nintendo Black Star Promos', null),
  ('p-a', 'Promos-A', null),
  ('pl1', 'Platinum', null),
  ('pl2', 'Rising Rivals', null),
  ('pl3', 'Supreme Victors', null),
  ('pl4', 'Arceus', null),
  ('pop1', 'POP Series 1', null),
  ('pop2', 'POP Series 2', null),
  ('pop3', 'POP Series 3', null),
  ('pop4', 'POP Series 4', null),
  ('pop5', 'POP Series 5', null),
  ('pop6', 'POP Series 6', null),
  ('pop7', 'POP Series 7', null),
  ('pop8', 'POP Series 8', null),
  ('pop9', 'POP Series 9', null),
  ('rc', 'Radiant Collection', null),
  ('rs', null, '紅寶石與藍寶石'),
  ('ru1', 'Pokémon Rumble', null),
  ('s-p', null, '劍盾 PROMO'),
  ('s10a', null, '黑暗亡靈'),
  ('s10b', null, 'Pokémon GO'),
  ('s10d', null, '時間觀察者'),
  ('s10p', null, '空間魔術師'),
  ('s11', null, '三連音爆'),
  ('s11a', null, '白熱奧祕'),
  ('s12', null, '思維激盪'),
  ('s12a', null, '天地萬物VSTAR'),
  ('s4', null, '驚天伏特攻擊'),
  ('s4a', null, '閃色明星V'),
  ('s5a', null, '雙璧戰士'),
  ('s5i', null, '一撃大師'),
  ('s5r', null, '連撃大師'),
  ('s6a', null, '伊布英雄'),
  ('s6h', null, '銀白戰槍'),
  ('s6k', null, '漆黑幽魂'),
  ('s7d', null, '摩天巔峰'),
  ('s7r', null, '蒼空烈流'),
  ('s8', null, '匯流藝術'),
  ('s8a', null, '25週年收藏款'),
  ('s8b', null, 'VMAX絕群壓軸'),
  ('s9', null, '星星誕生'),
  ('s9a', null, '對戰地區'),
  ('sc1a', null, '劍&盾 SET A'),
  ('sc1b', null, '劍&盾 SET B'),
  ('sc1d', null, '劍&盾'),
  ('sc2a', null, '無極力量 SET A'),
  ('sc2b', null, '無極力量 SET B'),
  ('sc2d', null, '無極力量'),
  ('sca', null, '搭檔'),
  ('scb', null, '挑戰'),
  ('scc', null, '進化'),
  ('scd', null, '強大'),
  ('sdl', null, '噴火龍'),
  ('sdm', null, '超夢'),
  ('sdp', null, '皮卡丘'),
  ('sh', null, '寶可夢卡牌家庭組合'),
  ('si', null, '初階牌組100'),
  ('si1', 'Southern Islands', null),
  ('sj', null, '藏瑪然特VS無極汰那'),
  ('sk', null, '頂級訓練家收藏箱 VSTAR'),
  ('sld', null, '起始組合VSTAR 達克萊伊'),
  ('sll', null, '起始組合VSTAR 路卡利歐'),
  ('sm', null, '太陽與月亮'),
  ('sm-p', null, '太陽月亮 PROMO'),
  ('sm1', 'Sun & Moon', '太陽'),
  ('sm10', 'Unbroken Bonds', '雙重衝擊'),
  ('sm11', 'Unified Minds', '改變之道'),
  ('sm115', 'Hidden Fates', null),
  ('sm11a', null, '重鎚GX'),
  ('sm12', 'Cosmic Eclipse', '宇宙日蝕'),
  ('sm2', 'Guardians Rising', '月亮'),
  ('sm3', 'Burning Shadows', '草原旋風'),
  ('sm3.5', 'Shining Legends', null),
  ('sm3a', null, '幻光奇蹟'),
  ('sm3h', null, '神秘時代'),
  ('sm4', 'Crimson Invasion', '閃耀傳說'),
  ('sm4a', null, '獨特光輝'),
  ('sm5', 'Ultra Prism', '超越極限'),
  ('sm5m', null, '秘境競技場'),
  ('sm5s', null, '太陽與月亮 GX'),
  ('sm6', 'Forbidden Light', '禁忌光之章'),
  ('sm6a', null, '禁忌地球'),
  ('sm7', 'Celestial Storm', '升龍之達人'),
  ('sm7.5', 'Dragon Majesty', null),
  ('sm7a', null, '夜行奇蹟'),
  ('sm8', 'Lost Thunder', '爆發光輝'),
  ('sm8a', null, '電擊GX'),
  ('sm9', 'Team Up', '標記對決'),
  ('sm9a', null, '夢之島冒險'),
  ('sma', 'Hidden Fates Shiny Vault', null),
  ('smp', 'SM Black Star Promos', null),
  ('sn', null, '初階牌組100 特別版'),
  ('sp', 'Sample', null),
  ('sp5', null, '強大'),
  ('sp6', null, 'VSTAR特別組合'),
  ('spd', null, 'VSTAR&VMAX 高級牌組 代歐奇希斯'),
  ('spz', null, 'VSTAR&VMAX 高級牌組 捷拉奧拉'),
  ('ss', null, '劍與盾'),
  ('ss1', null, '劍'),
  ('ss10', null, '時空奧秘'),
  ('ss11', null, '失落深淵'),
  ('ss12', null, '黎明輝光'),
  ('ss12a', null, '寶可夢GO'),
  ('ss2', null, '盾'),
  ('ss3', null, '黑暗幻影'),
  ('ss4', null, '出擊！炎拳'),
  ('ss5', null, '摩天浮冰'),
  ('ss5a', null, '雙王牌對決'),
  ('ss6', null, '銀色暴風雪'),
  ('ss6a', null, '100週年紀念系列'),
  ('ss7', null, '藍天流星'),
  ('ss7a', null, '極巔之頂'),
  ('ss8', null, '融合力量'),
  ('ss8a', null, '25週年黃金盒'),
  ('ss9', null, '星之誕生'),
  ('sv', null, '朱與紫'),
  ('sv-p', null, '特典卡 朱&紫'),
  ('sv01', 'Scarlet & Violet', null),
  ('sv02', 'Paldea Evolved', null),
  ('sv03', 'Obsidian Flames', null),
  ('sv03.5', '151', null),
  ('sv04', 'Paradox Rift', null),
  ('sv04.5', 'Paldean Fates', null),
  ('sv05', 'Temporal Forces', null),
  ('sv06', 'Twilight Masquerade', null),
  ('sv06.5', 'Shrouded Fable', null),
  ('sv07', 'Stellar Crown', null),
  ('sv08', 'Surging Sparks', null),
  ('sv08.5', 'Prismatic Evolutions', null),
  ('sv09', 'Journey Together', null),
  ('sv1', null, '朱色'),
  ('sv10', 'Destined Rivals', '火箭隊的榮耀'),
  ('sv10.5b', 'Black Bolt', null),
  ('sv10.5w', 'White Flare', null),
  ('sv1a', null, '三連音爆'),
  ('sv1s', null, '朱ex'),
  ('sv1v', null, '紫ex'),
  ('sv2', null, '紫色'),
  ('sv2a', null, '寶可夢卡牌151'),
  ('sv2d', null, '碟旋暴擊'),
  ('sv2p', null, '冰雪險境'),
  ('sv3', null, '黯焰支配者'),
  ('sv3a', null, '激狂駭浪'),
  ('sv4', null, '古代的咆哮'),
  ('sv4a', null, '閃色寶藏ex'),
  ('sv4k', null, '古代咆哮'),
  ('sv4m', null, '未來閃光'),
  ('sv5a', null, '緋紅薄霧'),
  ('sv5k', null, '狂野之力'),
  ('sv5m', null, '異度審判'),
  ('sv6', null, '變幻假面'),
  ('sv6a', null, '黑夜漫遊者'),
  ('sv7', null, '星晶奇跡'),
  ('sv7a', null, '樂園騰龍'),
  ('sv8', null, '超電突圍'),
  ('sv8a', null, '太晶慶典ex'),
  ('sv9', null, '對戰搭檔'),
  ('sv9a', null, '熱風競技場'),
  ('sval', null, '起始組合ex 呆火鱷&電龍 ex'),
  ('svam', null, '起始組合ex 新葉喵&路卡利歐 ex'),
  ('svaw', null, '起始組合ex 潤水鴨&謎擬Ｑ ex'),
  ('svb', null, '頂級訓練家收藏箱ex'),
  ('svc', null, '皮卡丘特別組合'),
  ('svd', null, 'ex初階牌組'),
  ('sve', 'Scarlet & Violet Energy', null),
  ('svel', null, '骨紋巨聲鱷ex'),
  ('svem', null, '超夢ex'),
  ('svf', null, '黯焰支配者'),
  ('svhk', null, '未來密勒頓ex'),
  ('svhm', null, '閃色寶藏ex'),
  ('svp', 'SVP Black Star Promos', null),
  ('svp1', null, 'ex特別組合'),
  ('swsh1', 'Sword & Shield', null),
  ('swsh10', 'Astral Radiance', null),
  ('swsh10.5', 'Pokémon GO', null),
  ('swsh11', 'Lost Origin', null),
  ('swsh12', 'Silver Tempest', null),
  ('swsh12.5', 'Crown Zenith', null),
  ('swsh2', 'Rebel Clash', null),
  ('swsh3', 'Darkness Ablaze', null),
  ('swsh3.5', 'Champion''s Path', null),
  ('swsh4', 'Vivid Voltage', null),
  ('swsh4.5', 'Shining Fates', null),
  ('swsh5', 'Battle Styles', null),
  ('swsh6', 'Chilling Reign', null),
  ('swsh7', 'Evolving Skies', null),
  ('swsh8', 'Fusion Strike', null),
  ('swsh9', 'Brilliant Stars', null),
  ('swshp', 'SWSH Black Star Promos', null),
  ('tk-bw-e', 'BW trainer Kit (Excadrill)', null),
  ('tk-bw-z', 'BW trainer Kit (Zoroark)', null),
  ('tk-dp-l', 'DP trainer Kit (Lucario)', null),
  ('tk-dp-m', 'DP trainer Kit (Manaphy)', null),
  ('tk-ex-latia', 'EX trainer Kit (Latias)', null),
  ('tk-ex-latio', 'EX trainer Kit (Latios)', null),
  ('tk-ex-m', 'EX trainer Kit 2 (Minun)', null),
  ('tk-ex-p', 'EX trainer Kit 2 (Plusle)', null),
  ('tk-hs-g', 'HS trainer Kit (Gyarados)', null),
  ('tk-hs-r', 'HS trainer Kit (Raichu)', null),
  ('tk-sm-l', 'SM trainer Kit (Lycanroc)', null),
  ('tk-sm-r', 'SM trainer Kit (Alolan Raichu)', null),
  ('tk-xy-b', 'XY trainer Kit (Bisharp)', null),
  ('tk-xy-latia', 'XY trainer Kit (Latias)', null),
  ('tk-xy-latio', 'XY trainer Kit (Latios)', null),
  ('tk-xy-n', 'XY trainer Kit (Noivern)', null),
  ('tk-xy-p', 'XY trainer Kit (Pikachu Libre)', null),
  ('tk-xy-su', 'XY trainer Kit (Suicune)', null),
  ('tk-xy-sy', 'XY trainer Kit (Sylveon)', null),
  ('tk-xy-w', 'XY trainer Kit (Wigglytuff)', null),
  ('wp', 'W Promotional', null),
  ('xy', null, 'XY'),
  ('xy-p', null, 'XY PROMO'),
  ('xy0', 'Kalos Starter Set', null),
  ('xy1', 'XY', 'XY'),
  ('xy10', 'Fates Collide', '龍之嘶吼'),
  ('xy11', 'Steam Siege', '次元風暴'),
  ('xy12', 'Evolutions', '蒸汽圍攻'),
  ('xy2', 'Flashfire', '閃光之戒'),
  ('xy3', 'Furious Fists', '超速進化'),
  ('xy4', 'Phantom Forces', '邁向幻境'),
  ('xy5', 'Primal Clash', '古代的原動力'),
  ('xy5g', null, '原初的力量'),
  ('xy6', 'Roaring Skies', '暴烈天空'),
  ('xy7', 'Ancient Origins', '極速連勝'),
  ('xy8', 'BREAKthrough', '斷裂時空'),
  ('xy9', 'BREAKpoint', '超級傳說'),
  ('xya', 'Yellow A Alternate', null),
  ('xyp', 'XY Black Star Promos', null)
on conflict (set_id) do update set en = excluded.en, zh = excluded.zh;
